### ISSUE TITLE
디벨롭을 해봅시다!

### ISSUE THREAD

**Issue by joshyeom** [How-weather/front#60]
## Description

디벨롭을 하기위해서는 어떤것들을 해야할까요? 하나씩 의견을 주신다면 List에 추가해보고 의견을 나눠보죠

강제되는것은 아니지만! 참여율과 동기부여를 위해 데드라인 및 할당량과 스크럼을 만들면 어떨까요? 부담, 무리 안되는 선에서 의견을 모아보아요!

## TodoList

- Typescript 도입 - **조쉬**

- 위치 설정/수정 기능이 지금은 다중선택 필드로 되어있는데 사용자가 직접 서치해서 상세설정 하는걸로 디벨롭 
ex) 텍스트필드 ~군/구로 검색->검색결과 도출->선택 후 수정 - **나무**

- 로그인 / 회원가입 서비스 페이지 - **나무**

<br>
<br>

## Work

- 1주일에 2개의 액션 아이템(https://blog.clap.company/1on1_actionitem/) 스크럼 전까지 완료하기 - 조쉬

<br>
<br>

## Scrum

- 1주일에 1번 전체 스크럼( 회의 ) - 조쉬

<br>
<br>

## ETC

댓글을 달아주시면 제가 List에 닉네임과 함께 올려드리겠습니다. 의견은 중복 가능!!

**Comment by mogin032** [comment]
-위치 설정/수정 기능이 지금은 다중선택 필드로 되어있는데 사용자가 직접 서치해서 상세설정 하는걸로 디벨롭 가능할까요...? 
ex) 텍스트필드 ~군/구로 검색->검색결과 도출->선택 후 수정

-로그인/회원가입 서비스 페이지
